* bash Basics

Generally speaking, a shell is any user interface to the UNIX operating system.

** What is a shell?

The shell's job is to translate the user's command lines into operating system instructions. You input a
command like:
: ls -l | sort

Shell will break up the line into words, determine the purpose of each word, set up the I/O according to > or
some standard, implicit instructions, and fine the commands and run it with the options and arguments. 

Remember that the shell itself is not UNIX-just the user interface to it.

** Bash

Two ways to use bash:

1. a user interface
2. a programming enviroment

*$SHELL* can tell you which shell you are using.

Command in my CentOS5 to find out where bash is:

: which bash
: whereis bash
: grep bash /etc/passwd | awk -F: '{print $7}' | sort -u

use *chsh* to change your login shell.

** Commands, Arguments and options

The first word on the line is the command. The rest are arguments (also called parameters) to the command. An
option is a special type of argument that gives teh command specific infomation on what it is supposed t
do. Options usually consist of a dash followed by a letter.

** Files

Three types are by far the most important:

1. Regular files
2. Executable files
3. Directories

: cd - #change to whatever directory you were n before the current one

*** Filenames, wildcards

Filenames are so important in UNIX that the shell provides a built-in way t specify the pattern of a set of
filenames without having to know all of the names themselves. You can use special characters, called
wildcards, in filenames to turn them into patterns.

: ?  Any single character
: *  Any string of characters
: [set] Any character in set
: [!set] Any character not in set

There is nothing special about the dot (.) in UNIX filenames (aside from the leading dot, which "hides " the
file); it's just another character.

: ls * # list all files in the current directory
: ls *.* # only list those that have at least one dot in the middle of the name

wildcard expansion.

The commands that you run only see the results of wildcard expansion
The command will see the filenames just as if they were all typed in individually.

*** Brace expanision
=echo a{b,c,d}e=
will get
=abe ace ade=
** Input and Output
The UNIX I/O scheme is based on two dazzlingly simple ideas. 
1. UNIX file I/O takes the form of arbitrarily long sequences of characters.
2. everything on the system that produces or accepts data is treated as a file, this includes hardware devices
   like disk drives and terminals.

*** Standard I/O

Each program that you invoke has all three standard I/O channels set to your terminal or workstation, so that
standard input is your keyboard, and standard output and error are your screen or window.

When necessary, you can redirect input and output to come from or go to a file instead. 

Poputar UNIX data filering utilities

: cat        copy input to output
: grep       search for strings in the input
: sort       sort lines in the input
: cut        extract columns from input
: set        perform editing operations on input
: tr         translate characters in the input to other characters

*** I/O Redirection

=using < >=
pipeline : redirect the output of a command into the standard input of another
command. |
** Job
   "Doing more than one thing at a time" means running more than one program at the same time. You do this when
you invoke a pipeline.

Using & to run a command in the background. 
Check on background jobs with the command *jobs*.

Jobs you put in the background should not do I/O to your terminal. If you want to run a job in the background
that expects standard input or produces standard output, you usually want wo redirect the I/O so that it comes
from or goes to a file.
** Command line edit
.bash_history in home directory records commands that you type into the shell. 

: [zhangwl@localhost zhangwl]$ echo $HISTFILE
: /jeda/home/zhangwl/.bash_history

Whenever you enter a command,  you are telling the shell to run that command in a subprocess, and some coplex
programs may start their own subprocesses.

two ways to run a shell script
1. using source command, this causes the commands in the script to be read and run as if you typed them in.
2. using the script file's name.
** Functions

A function is sort of a script-within-a-script, you use it to define some shell code by name and store it in
the shell's memory, to be invoked and run later.

The shell predefines some environment variables when you log in.
positional parameters: hold the command-line arguments to scripts when they are invoked. Positional parameters
have the names 1, 2, 3, etc., meaning that their values are denoted by $1, $2, $3, etc. There is also a
positional parameter 0, whose value is the name of the script.

Two special variables contain all of the positional parameters (except positional parameter 0): * and @.

"$*" is a single string that consists of all of the positional parameters, separated by the first character in
the value of the environment variable IFS.
"$@" is equal to "$1" "$2" "$3"..."$N", where N is the number of positional parameters. That is, it's equal to
N separate double-quoted strings, which are separated by spaces.

Vairable # holds the number of positional parameters (as a character string). 

All of these varaibles are "read-only".

Variables defined within functions are not local, they are global, meaning that their values are known
throughout the entire shell script.

** Local variables in Functions
A local statement inside a function definition  makes the variables involved all become local to that
function. 

#+TITLE:     Shell Learning Notes
#+AUTHOR:    Zhang Wenliang
#+EMAIL:     wlamos@gmail.com
#+DATE:      2010-12-23 Thu
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 

